### PR TITLE
Merge DEV-20181005

### PR DESCRIPTION
**Pull request by TimothyZhang023**

### CODE REVIEW

**Comment by TimothyZhang023** [comment]
@Trumeet

**Comment by Trumeet** [comment]
@TimothyZhang023 https://github.com/Trumeet/MiPushFramework/pull/196/files#diff-20d33d6d87a923c353afb66866dd4456R293 这里是从小米 SDK 里面弄出来的？

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 https://github.com/Trumeet/MiPushFramework/pull/196/files#diff-20d33d6d87a923c353afb66866dd4456R293 这里是从小米 SDK 里面弄出来的？

 
亮屏这个不是

**Comment by Trumeet** [comment]
OK, thanks

**Comment by TimothyZhang023** [comment]
to solve some rom (oneplus) the notification bar icon issue 
transparent icon not turn black under the white background

https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/com/android/internal/util/NotificationColorUtil.java

```
  /**
     * Checks whether a Bitmap is a small grayscale icon.
     * Grayscale here means "very close to a perfect gray"; icon means "no larger than 64dp".
     *
     * @param bitmap The bitmap to test.
     * @return True if the bitmap is grayscale; false if it is color or too large to examine.
     */
    public boolean isGrayscaleIcon(Bitmap bitmap) {
        // quick test: reject large bitmaps
        if (bitmap.getWidth() > mGrayscaleIconMaxSize
                || bitmap.getHeight() > mGrayscaleIconMaxSize) {
            return false;
        }
.......

```
mGrayscaleIconMaxSize is 64dp 
so bitmap icon size must small than 64dp : )

**Comment by Trumeet** [comment]
It's OK, thank you. But I still think there are something bad if you set BroadcastReceiver as static var and register it in Util class...

**Pull request merged**
