### PR TITLE
Added German & English localization

### PR DESCRIPTION
**Pull request by AlNoes**

### CODE REVIEW

**Comment by 95e2** [comment]
喵喵喵？国内的推送服务歪果仁又不用

**Comment by AlNoes** [comment]
对不起，我不会说中文。 （我希望谷歌翻译是足够好的）。
你的意思是，项目中的推送构建目标不再使用了吗？
那么它应该被删除...
我翻译了所有strings.xml并在本地进行了测试。

I'm sorry, I don't speak Chinese. (I hope Google translator is good enough).
Do you mean, the push build target inside the project is not used anymore?
Then it should be removed...
I translated all strings.xml and testet it locally.

**Comment by 95e2** [comment]
@AlNoes I mean this Project is for China only
@TimothyZhang023 我没说错吧？这个是只能国内用的吧？

**Comment by 95e2** [comment]
@AlNoes As far as I know, GCM or FCM can be used anywhere except in China. This project is like GCM or FCM, just a nmessage push project.

**Comment by TimothyZhang023** [comment]
Most of people using this project are Chinese , so i am not sure German support is essential . 
and project is currently under development  add  German support may come to be a burden to due we are not familiar with it .
so,  my option is we are going to support Chinese and English . German is not under our consideration.

**Comment by adligithub** [comment]
#136 
Duplicate of #

**Comment by wangzhao2222** [comment]
I am curious about which FOREIGN apps have supported mi push.

**Comment by AlNoes** [comment]
Sure thing. I only added German as it is my mother tongue ;)

**Comment by Zxilly** [comment]
MiPush Framework is a regional service,most of the apps which out of China didn't have the support for MiPush at all,it just work as the replacement of the FCM(BLOCK BY CHINA)

**Comment by Trumeet** [comment]
Thanks a lot. We are reviewing translatuons, thank you! 😆

**Pull request closed without merging**
